### ISSUE TITLE
Use NPM for dependencies, instead of Bower

### ISSUE THREAD

**Issue by 0xrohan10** [zach-adams/sprig#9]
There's no need to have a second package manager when NPM can handle adding in jQuery and Bootstrap. Prior to NPM 3, the only real benefit of Bower was the flat dependency tree, but now with NPM 3+, that is no longer the case.

**Comment by gianpaj** [comment]
That sounds interesting @rohannair. Could you point to a link or example on how to do this? I couldn't find straight way on Google. Thanks
